// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTj1MpWkBsuEYP4tGZ8Wf33dxy3jUpiV0',
    appId: '1:89325901306:web:fa6518c986a7bb0c42c043',
    messagingSenderId: '89325901306',
    projectId: 'proyecto-receptaculo',
    authDomain: 'proyecto-receptaculo.firebaseapp.com',
    databaseURL: 'https://proyecto-receptaculo-default-rtdb.firebaseio.com',
    storageBucket: 'proyecto-receptaculo.firebasestorage.app',
    measurementId: 'G-SQQ30M5V07',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRAc6lfXEtsGewb-RcX6nuF-QKcPG08L8',
    appId: '1:89325901306:android:896797b109e05f7e42c043',
    messagingSenderId: '89325901306',
    projectId: 'proyecto-receptaculo',
    databaseURL: 'https://proyecto-receptaculo-default-rtdb.firebaseio.com',
    storageBucket: 'proyecto-receptaculo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzlicHxtWCQ12PL8w5kEFZ6tulr4CoFbo',
    appId: '1:89325901306:ios:ccc04fb419576d0f42c043',
    messagingSenderId: '89325901306',
    projectId: 'proyecto-receptaculo',
    databaseURL: 'https://proyecto-receptaculo-default-rtdb.firebaseio.com',
    storageBucket: 'proyecto-receptaculo.firebasestorage.app',
    iosBundleId: 'com.example.proyectoReceptaculo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzlicHxtWCQ12PL8w5kEFZ6tulr4CoFbo',
    appId: '1:89325901306:ios:ccc04fb419576d0f42c043',
    messagingSenderId: '89325901306',
    projectId: 'proyecto-receptaculo',
    databaseURL: 'https://proyecto-receptaculo-default-rtdb.firebaseio.com',
    storageBucket: 'proyecto-receptaculo.firebasestorage.app',
    iosBundleId: 'com.example.proyectoReceptaculo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTj1MpWkBsuEYP4tGZ8Wf33dxy3jUpiV0',
    appId: '1:89325901306:web:1dcdfb10481c4ac342c043',
    messagingSenderId: '89325901306',
    projectId: 'proyecto-receptaculo',
    authDomain: 'proyecto-receptaculo.firebaseapp.com',
    databaseURL: 'https://proyecto-receptaculo-default-rtdb.firebaseio.com',
    storageBucket: 'proyecto-receptaculo.firebasestorage.app',
    measurementId: 'G-C3DFPSY5MR',
  );

}